const st = {
  ARRAY: /*                   */ "ARRAY",
  ASSIGNMENT: /*              */ "ASSIGNMENT",
  BINARY_OPERATOR: /*         */ "BINARY_OPERATOR",
  ENUM_DEFINITION: /*         */ "ENUM_DEFINITION",
  FUNCTION_CALL_ARGS: /*      */ "FUNCTION_CALL_ARGS",
  FUNCTION_DEC_ARGS: /*       */ "FUNCTION_DEC_ARGS",
  FUNCTION_DEC_BODY: /*       */ "FUNCTION_DEC_BODY",
  GENERIC_EXPRESSION: /*      */ "GENERIC_EXPRESSION",
  IF_BODY: /*                 */ "IF_BODY",
  IF_CONDITION: /*            */ "IF_CONDITION",
  IF_ELSE: /*                 */ "IF_ELSE",
  LAMBDA_ARGS: /*             */ "LAMBDA_ARGS",
  LAMBDA_BODY: /*             */ "LAMBDA_BODY",
  OBJECT_KEY: /*              */ "OBJECT_KEY",
  OBJECT_VALUE: /*            */ "OBJECT_VALUE",
  ROOT: /*                    */ "ROOT",
  STRUCT_DEFINITION: /*       */ "STRUCT_DEFINITION",
  STRUCT_KEY: /*              */ "STRUCT_KEY",
  STRUCT_VALUE: /*            */ "STRUCT_VALUE",
  TRY_BODY: /*                */ "TRY_BODY",
  TRY_HANDLER_PATTERN: /*     */ "TRY_HANDLER_PATTERN",
  TRY_HANDLER_BODY: /*        */ "TRY_HANDLER_BODY",
  UNARY_OPERATOR: /*          */ "UNARY_OPERATOR",
}

module.exports = st
