// Character types
const ct = {
  CT_AMPERSAND: /*        */ "CT_AMPERSAND",
  CT_ASTERISK: /*         */ "CT_ASTERISK",
  CT_BACKSLASH: /*        */ "CT_BACKSLASH",
  CT_BANG: /*             */ "CT_BANG",
  CT_COLON: /*            */ "CT_COLON",
  CT_COMMA: /*            */ "CT_COMMA",
  CT_DOLLAR_SIGN: /*      */ "CT_DOLLAR_SIGN",
  CT_DOUBLE_QUOTE: /*     */ "CT_DOUBLE_QUOTE",
  CT_EQUALS: /*           */ "CT_EQUALS",
  CT_GREATER_THAN: /*     */ "CT_GREATER_THAN",
  CT_HASH: /*             */ "CT_HASH",
  CT_HYPHEN: /*           */ "CT_HYPHEN",
  CT_IDENTIFIER: /*       */ "CT_IDENTIFIER",
  CT_LEFT_BRACKET: /*     */ "CT_LEFT_BRACKET",
  CT_LEFT_CURLY: /*       */ "CT_LEFT_CURLY",
  CT_LEFT_PAREN: /*       */ "CT_LEFT_PAREN",
  CT_LESS_THAN: /*        */ "CT_LESS_THAN",
  CT_NUMBER: /*           */ "CT_NUMBER",
  CT_PERCENT: /*          */ "CT_PERCENT",
  CT_PERIOD: /*           */ "CT_PERIOD",
  CT_PIPE: /*             */ "CT_PIPE",
  CT_PLUS_SIGN: /*        */ "CT_PLUS_SIGN",
  CT_RIGHT_BRACKET: /*    */ "CT_RIGHT_BRACKET",
  CT_RIGHT_CURLY: /*      */ "CT_RIGHT_CURLY",
  CT_RIGHT_PAREN: /*      */ "CT_RIGHT_PAREN",
  CT_SINGLE_QUOTE: /*     */ "CT_SINGLE_QUOTE",
  CT_SLASH: /*            */ "CT_SLASH",
  CT_UNDERSCORE: /*       */ "CT_UNDERSCORE",
  CT_WHITESPACE: /*       */ "CT_WHITESPACE",
}

module.exports = ct
