// Character types
const ct = {
  CT_AMPERSAND: /*        */ "CT_AMPERSAND",
  CT_ASTERISK: /*         */ "CT_ASTERISK",
  CT_BACKSLASH: /*        */ "CT_BACKSLASH",
  CT_BANG: /*             */ "CT_BANG",
  CT_COLON: /*            */ "CT_COLON",
  CT_COMMA: /*            */ "CT_COMMA",
  CT_DOLLAR_SIGN: /*      */ "CT_DOLLAR_SIGN",
  CT_DOUBLE_QUOTE: /*     */ "CT_DOUBLE_QUOTE",
  CT_EQUALS: /*           */ "CT_EQUALS",
  CT_GREATER_THAN: /*     */ "CT_GREATER_THAN",
  CT_HASH: /*             */ "CT_HASH",
  CT_HYPHEN: /*           */ "CT_HYPHEN",
  CT_IDENTIFIER: /*       */ "CT_IDENTIFIER",
  CT_LEFT_BRACKET: /*     */ "CT_LEFT_BRACKET",
  CT_LEFT_CURLY: /*       */ "CT_LEFT_CURLY",
  CT_LEFT_PAREN: /*       */ "CT_LEFT_PAREN",
  CT_LESS_THAN: /*        */ "CT_LESS_THAN",
  CT_NUMBER: /*           */ "CT_NUMBER",
  CT_PERCENT: /*          */ "CT_PERCENT",
  CT_PERIOD: /*           */ "CT_PERIOD",
  CT_PIPE: /*             */ "CT_PIPE",
  CT_PLUS_SIGN: /*        */ "CT_PLUS_SIGN",
  CT_RIGHT_BRACKET: /*    */ "CT_RIGHT_BRACKET",
  CT_RIGHT_CURLY: /*      */ "CT_RIGHT_CURLY",
  CT_RIGHT_PAREN: /*      */ "CT_RIGHT_PAREN",
  CT_SINGLE_QUOTE: /*     */ "CT_SINGLE_QUOTE",
  CT_SLASH: /*            */ "CT_SLASH",
  CT_UNDERSCORE: /*       */ "CT_UNDERSCORE",
  CT_WHITESPACE: /*       */ "CT_WHITESPACE",
}

const characterRanges = {
  [ct.CT_AMPERSAND]: /*         */ [["&"]],
  [ct.CT_ASTERISK]: /*          */ [["*"]],
  [ct.CT_BACKSLASH]: /*         */ [["\\"]],
  [ct.CT_BANG]: /*              */ [["!"]],
  [ct.CT_COLON]: /*             */ [[":"]],
  [ct.CT_COMMA]: /*             */ [[","]],
  [ct.CT_DOLLAR_SIGN]: /*       */ [["$"]],
  [ct.CT_DOUBLE_QUOTE]: /*      */ [['"']],
  [ct.CT_EQUALS]: /*            */ [["="]],
  [ct.CT_GREATER_THAN]: /*      */ [[">"]],
  [ct.CT_HASH]: /*              */ [["#"]],
  [ct.CT_HYPHEN]: /*            */ [["-"]],
  [ct.CT_IDENTIFIER]: /*        */ [
    ["a", "z"],
    ["A", "Z"],
  ],
  [ct.CT_LEFT_BRACKET]: /*      */ [["["]],
  [ct.CT_LEFT_CURLY]: /*        */ [["{"]],
  [ct.CT_LEFT_PAREN]: /*        */ [["("]],
  [ct.CT_LESS_THAN]: /*         */ [["<"]],
  [ct.CT_NUMBER]: /*            */ [["0", "9"]],
  [ct.CT_PERCENT]: /*           */ [["%"]],
  [ct.CT_PERIOD]: /*            */ [["."]],
  [ct.CT_PIPE]: /*              */ [["|"]],
  [ct.CT_PLUS_SIGN]: /*         */ [["+"]],
  [ct.CT_RIGHT_BRACKET]: /*     */ [["]"]],
  [ct.CT_RIGHT_CURLY]: /*       */ [["}"]],
  [ct.CT_RIGHT_PAREN]: /*       */ [[")"]],
  [ct.CT_SINGLE_QUOTE]: /*      */ [["'"]],
  [ct.CT_SLASH]: /*             */ [["/"]],
  [ct.CT_UNDERSCORE]: /*        */ [["_"]],
  [ct.CT_WHITESPACE]: /*        */ [["\n"], ["\t"], [" "]],
}

module.exports = { characterRanges, ...ct }
